### ISSUE TITLE
Add backup to local file feature

### ISSUE THREAD

**Issue by Keith94** [alexpdraper/reading-list#10]
AFAIK there's no easy way to backup and restore pages from the reading list between Firefox profiles.

**Comment by whitecat** [comment]
@alexpdraper  This would be a setting. So one more setting to put on the list.

**Comment by alexpdraper** [comment]
What’s the use case here? A user has two different Firefox profiles and wants to copy their list from one profile to other? Or have the reading lists synced between the two profiles?

Presuming it’s the former, we could create a tool for downloading and uploading a reading list. If it’s the latter that’s a whole different ball game, as we’d have to abandon the Firefox/Chrome Extension Storage API.

Alternately, if we’re talking about syncing across multiple browsers that are logged in as the same user, that should already be happening. From MDN:

> Items in sync storage are synced by the browser, and are available across all instances of that browser that the user is logged into (e.g. via Firefox sync, or a Google account), across different devices.

@Keith94 What were you thinking?

**Comment by Keith94** [comment]
>A user has two different Firefox profiles and wants to copy their list from one profile to other?

Yes, I meant that one. I want basic export and import functionality, like many add-ons out there also have (uBlock Origin, Stylus, Tampermonkey, etc.) e.g.:

![image](https://user-images.githubusercontent.com/5490615/31471711-1120074a-ae9f-11e7-8b5b-045bbe9a946f.png)

**Comment by whitecat** [comment]
That looks great!

**Comment by whitecat** [comment]
I finished the import export buttons. 
I will push the changes with the next upload.
<img width="185" alt="screen shot 2017-10-15 at 4 39 40 pm" src="https://user-images.githubusercontent.com/122229/31590589-a0772222-b1c7-11e7-97e0-605c21daef57.png">

**Comment by whitecat** [comment]
@Keith94  Here is the pull request https://github.com/alexpdraper/reading-list/pull/21. Let me know if you want anything different.

**Comment by whitecat** [comment]
@Keith94 What do you expect to happen on import if you already have items in your reading list, They are all deleted and the import over writes everything, or all non existing links are just added with the one currently there?

**Comment by Keith94** [comment]
Good question! I'd expect it to work like "Import and append" so the new links are added to existing items. Importing should also skip duplicate items if they're already added, too.

**Comment by Keith94** [comment]
@whitecat Thanks for adding the backup feature! It really comes in handy. :)
