### ISSUE TITLE
problem in firefox

### ISSUE THREAD

**Issue by Techrese** [alexpdraper/reading-list#128]
I use reading list in chrome and want to use it in firefox, however i do not see the reading list icon in the top right corner like it's in chrome.

Any help on this?

**Comment by alexpdraper** [comment]
I believe there should be a menu option for customize toolbar. From there you should be able to find it and drag it into the top.

<img width="336" alt="Screenshot 2021-04-28 at 9 11 11 AM" src="https://user-images.githubusercontent.com/6441503/116436875-ae70e500-a801-11eb-807a-7659f78aee59.png">

**Comment by Techrese** [comment]
Hmm thanks for the info, but no i don't find the reading list in the customize toolbar section , it's kinda strange :/
