### ISSUE TITLE
Where's reading list data stored?

### ISSUE THREAD

**Issue by xmgz** [alexpdraper/reading-list#18]
I dont have the knowlage to read and understand the extension code and how it works, but I'd like to know where is that list (containing personal data) stored.  May it be set to a local storage location preferably than google servers? (I'm using chromium with google session account). This file could be located on a personal cloud file system and that could allow to share between computers on diferent OSs.

Sorry if already discused or if this implementation has been solved successfully using other methods. It's a honest question and/or feature request. Thanks

Or... just a nonsense question.

**Comment by whitecat** [comment]
Local storage is a possible feature that can be added in the future but it is not on our road map. 
To do this you would need change all calls to `chrome.storage.sync`, and add an option in the settings menu that checks where the user wants his information stored. If you want to create a pull request that would be awesome.

From what I can tell all data stored on the servers are encrypted with your google/firefox credentials. \[[1](https://superuser.com/questions/753465/im-using-chrome-and-chrome-sync-does-google-have-access-to-my-passwords)\]

**Comment by alexpdraper** [comment]
The synced storage is **not** encrypted by default (at least not on Chrome). If you want to encrypt your synced data, go to your [Chrome Sync Settings](chrome://settings/syncSetup) and select “encrypt synced data with your own sync passphrase.”

Also, if you want to store your data locally you can turn sync off for extensions from the same page. If sync is disabled or if you aren’t connected to the internet `chrome.storage.sync` works the same as local storage.

See: https://developer.chrome.com/extensions/storage

**Comment by whitecat** [comment]
I am closing this issue. I think it is resolved, no use creating a setting that already exists.
