### ISSUE TITLE
Access to ajax.googleapis.com

### ISSUE THREAD

**Issue by najjara** [alexpdraper/reading-list#19]
Why would a local addon need an external AJAX library? From Google no less?

The new version doesn't seem to bring new features, yet requires access to ajax.googleapis.com. The mere request sent to googleapis.com violates the user's privacy. There isn't even an option to block the outgoing requests to the saved sites for the favicons (which entails cookies and a sent request to the saved site)

Not a privacy conscious addon at all, despite its usefulness.

**Comment by whitecat** [comment]
We actually don't need it so we will take it out, but ajax.googleapis.com has been in since the very beginning of the app not since the new version..
