### ISSUE TITLE
Add current date to exported file

### ISSUE THREAD

**Issue by Keith94** [alexpdraper/reading-list#26]
It would be helpful if the current date was appended to the json file name. 

Suggested format: `readinglist-YYYY-MM-DD.json` i.e. `readinglist-2017-10-23.json`

Please and thank you!

**Comment by whitecat** [comment]
This also is a good idea. If you want to give it a try with a pull request that would be awesome.
The line that needs to change is [73 here](https://github.com/alexpdraper/reading-list/blob/3bf4ce0480442c003da52eeba82f6eda721c8929/js/options.js#L73).  That should have the date you suggest.

**Comment by smaragdus** [comment]
I would appreciate if export/import commands could be executed from the pop-up window- two new buttons for 'export' and 'import' beside 'settings' button.
