### ISSUE TITLE
Add Firefox to the Readme

### ISSUE THREAD

**Issue by Keith94** [alexpdraper/reading-list#27]
The current [README.md](https://github.com/alexpdraper/reading-list/blob/master/README.md) has no mention anywhere of a Firefox version. :(

Can you alter the document to make it browser agnostic?

Optional badge:

[![addons.mozilla.org/](https://addons.cdn.mozilla.net/static/img/addons-buttons/AMO-button_2.png)](https://addons.mozilla.org/firefox/addon/reading_list/)

**Comment by whitecat** [comment]
Can you make a pull request for this? I think that is a great idea.

**Comment by Keith94** [comment]
I never did that before, but I could try later.

**Comment by alexpdraper** [comment]
Ok. The README mentions Firefox now.
