### ISSUE TITLE
[Firefox] Animation is always enabled

### ISSUE THREAD

**Issue by Keith94** [alexpdraper/reading-list#28]
With Reading List 2.3.7, all the panel animations (e.g. adding pages to reading list) are always present, even with the "enable animation" option turned off in the settings.

**Comment by whitecat** [comment]
Um. So we disable open animation only. Do you see open animation disable when you turn off animations?

**Comment by Keith94** [comment]
Ah yeah, open animation does disable correctly. I thought the option referred to "all animations" by mistake.

**Comment by whitecat** [comment]
Nope this refers to only the open animation. We may change the other animations in the future. But that is more difficult, and we would add another setting, `disable all animations`.
