### ISSUE TITLE
Link to ratings

### ISSUE THREAD

**Issue by alexpdraper** [alexpdraper/reading-list#40]
For the amount of users we have, we don’t get a lot of ratings. I think we should include a link to the reviews page ([Chrome](https://chrome.google.com/webstore/detail/reading-list/lloccabjgblebdmncjndmiibianflabo/reviews) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/reading_list/reviews/)) to try to get that up.

**Comment by whitecat** [comment]
Where would this go bottom right and a link that says 'rate me'?

**Comment by whitecat** [comment]
Do you have a picture of what this looks like in the app?

**Comment by alexpdraper** [comment]
I do

<img width="360" alt="link-to-ratings" src="https://user-images.githubusercontent.com/6441503/38600987-f3f6098e-3d1a-11e8-93b8-3698c1077fe3.png">
