### ISSUE TITLE
Reset app button.

### ISSUE THREAD

**Issue by whitecat** [alexpdraper/reading-list#44]
Add a button to reset the app to default json.

**Comment by whitecat** [comment]
Should add confirmation. 
Need to refresh page after reset.

**Comment by whitecat** [comment]
Updated commit adds advanced options and confirm box

**Comment by whitecat** [comment]
SO MANY COMMITS! But I think we are nearing the end.
Here is the views:

<img width="399" alt="screen shot 2017-12-07 at 8 59 07 pm" src="https://user-images.githubusercontent.com/122229/33751740-cd8c4be0-db91-11e7-987c-fae7cb4a23ef.png">
<img width="394" alt="screen shot 2017-12-07 at 8 59 12 pm" src="https://user-images.githubusercontent.com/122229/33751741-cda2f868-db91-11e7-81e6-ed576492e633.png">
<img width="397" alt="screen shot 2017-12-07 at 8 59 19 pm" src="https://user-images.githubusercontent.com/122229/33751742-cdb845b0-db91-11e7-921f-2cd60bb96484.png">

**Comment by alexpdraper** [comment]
This still scares me so much.

**Comment by alexpdraper** [comment]
But I think this is a solid implementation.
