### ISSUE TITLE
Allow to add links

### ISSUE THREAD

**Issue by hklene** [alexpdraper/reading-list#49]
Can you please allow adding links to the list without opening them first?

I could imagine a Shift+click or a Ctrl+click. Also there could be a key-board-shortcut, to change the mouse-cursor into a crosshair if pointing to a link.

As a safe but lame way, there could also be a right-click-menu-entry.

**Comment by whitecat** [comment]
This looks like it is possible, and can be put on the road map. @alexpdraper what do you think?

**Comment by alexpdraper** [comment]
That’s definitely doable. I think the context menu (right-click menu) option is the best user experience of the options mentioned.

**Comment by whitecat** [comment]
A problem will occur when adding a link as both the fav icon, and title are no longer available to be retrieved.
Using this html: https://plus.google.com/_/favicon?domain_url=`<your url here>`  We can always load the fav icon.

I am not sure about title yet.

**Comment by whitecat** [comment]
Added the safe but `lame` way.

**Comment by hklene** [comment]
As for the two problems:
- The missing title can be filled with the link-text (as long, as it is not an image), otherwise fall back to the path of the URL, which might in many cases contain readable text.
- The missing icon can actually be a feature, to distinguish visited and unvisited links (#52 ). Just use a generic and unobtrusive grayish default-icon as a fall back.

**Comment by whitecat** [comment]
I agree the url may be missing text if you add using an image. I created a bug #76. You can follow the progress there.
We set the icon using googles url to identify the icon. Then when you visit the page the icon is improved.
