### ISSUE TITLE
Compact table view

### ISSUE THREAD

**Issue by hklene** [alexpdraper/reading-list#51]
Vertical screen-space is quite valuable, as widescreens don't offer as much, as it used to be. Please allow for an advanced table-view.

I'd like any link, to take only a single line in the hight of the standard-font (e.g. like the menu items). Though the structure should be tabular, don't draw lines, boxes, shadows and all the fancy bling-bling-stuff, just the data and maybe an alternating background, or a colored highlight on mouse hover.

In addition, I'd like more columns:
- icon
- title
- domain
- url
- date added
- time added

Clicking the column header should sort the list by that column, keeping a previous sort. The search could support an expression-language to address certain fields:
time: 9pm-10pm AND title: ^hello\s*world$

Of course, sort-order and filter should persist, until changed / reset.

**Comment by whitecat** [comment]
@hklene Can you show a mock up of how you would like this? I am having difficulties picturing the desired enhancement.

**Comment by hklene** [comment]
How about https://addons.cdn.mozilla.net/user-media/previews/full/63/63388.png?modified=1317219967
of https://addons.mozilla.org/de/firefox/addon/bookstack

Just with more columns and a pimped search field.

**Comment by alexpdraper** [comment]
This sounds like multiple issues:

  - Sort the list by different fields
  - Updated search
  - Theme with short rows

Initial thoughts: the list sorting and the theme could happen in the future. The search functionality could maybe happen as well, but I think we’re pretty happy with the search as it is, so it wouldn’t be a priority.

If you’d like these issues addressed, please break them up into separate issues.
