### ISSUE TITLE
Custom sort order

### ISSUE THREAD

**Issue by hklene** [alexpdraper/reading-list#56]
Allow to sort the link-list by:
- title-text
- domain (stripping subdomains and protocol)
- full-url
- date added (I did this last week)
- time added (I did this before lunch at work)

- make the sort stable (preserving previous order for equal cells)
- allow to reverse the order

This function will be toggled a few times, until you get it right, so hiding it in the options is not advisable. A natural representation would be the clickable column headers of a table, annotated with an arrow pointing up or down respectively.

Sort order is to persist until changed again. Newly added item should appear according to sort and removing some should not scramble sort.

Bonus: Allow multiple criteria to be selected for sorting.

Follow-up of #51

**Comment by alexpdraper** [comment]
What about a select box? Tabular layouts are a pain. They require a lot of horizontal space and would be a pretty big change to our current design, which people seem to like.

**Comment by hklene** [comment]
Horizontal space is only an issue, if you intend to show the list for longer. If the popup vanishes on selecting a link, I don't see a problem.
Yes, a select box will cover the easy cases. But it hinders selecting multiple sort criteria in a row. As the main list is already a popup, you wouldn't want a popup on top of a popup, will you?

**Comment by whitecat** [comment]
My first stab at sorting:
<img width="356" alt="Screen Shot 2020-09-03 at 1 08 41 AM" src="https://user-images.githubusercontent.com/122229/92073600-1b6ed080-ed82-11ea-9dbf-aa66acab94a9.png">
