### ISSUE TITLE
Cloud sync

### ISSUE THREAD

**Issue by PINCHO93** [alexpdraper/reading-list#8]
Would be really nice if we could sync our saves pages to the cloud, and to be synced accross devices.

**Comment by whitecat** [comment]
This is definitively a much more difficult task that may take a while to implement. Need to do more research to see if cloud sync is part of google API.

**Comment by whitecat** [comment]
This is already implemented in both Chrome, and Firefox. You have to be logged in for the sync to work across devices. The sync does not work between Firefox and Chrome. But it works between devices on each browser individually. 



Here is the Chrome Sync API documentation for the syncing:
https://developer.chrome.com/extensions/storage#property-sync

Here is the Firefox API:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage
