### ISSUE TITLE
Add page action

### ISSUE THREAD

**Issue by lepirata** [alexpdraper/reading-list#81]
Add an icon in the address bar that let's you add/remove a page faster to the reading list.

**Comment by whitecat** [comment]
Here is a picture of the add button in the address bar. I cannot find the button showing up in chrome. Can you add a picture where the add button is in the address bar?

<img width="1098" alt="screen shot 2018-03-11 at 8 45 41 pm" src="https://user-images.githubusercontent.com/122229/37260839-e5029718-256d-11e8-9851-943d87904fc1.png">

**Comment by whitecat** [comment]
Can you add an option, in the options menu to show/hide icon in the address bar?

**Comment by whitecat** [comment]
I like the idea I think implementation is very clean.

**Comment by lepirata** [comment]
Added the option in the options menu. 
Sadly Chrome doesn't let you have a page and browser action at the same time, so this feature is only available in Firefox.

**Comment by whitecat** [comment]
You want to give a hand on other issues for this project?

**Comment by lepirata** [comment]
I will. I'm adding the reading list to a sidebar.
I'm between projects and bored right now. If this continues I want to add
drag & drop to sort reading items and a compact design option.

**Comment by whitecat** [comment]
Awesome! Thank you for the help @lepirata
