### ISSUE TITLE
Link saved in reader view does not open anymore

### ISSUE THREAD

**Issue by ABuffEr** [alexpdraper/reading-list#95]
Hi,
first, thanks for this extension, I installed it a couple of days ago in Firefox 75 and loved immediately.
But... it seems to have problem with Firefox reader view functionality. In fact, if I visit this page, enable reader view and then add the page to reading list, the link:

about:reader?url=https%3A%2F%2Fwww.wired.it%2Fgadget%2Faccessori%2F2020%2F04%2F08%2Fdispenser-sapone-ascolto-brani-spotify%2F

cannot open. :(

**Comment by alexpdraper** [comment]
That's a curious one! I have been able to reproduce. I'll see what we can do to fix it.

**Comment by ABuffEr** [comment]
Thanks :) I'm continuing to use your extension, but disable reading mode each time before adding to list is quite unconfortable indeed ;)
