### ISSUE TITLE
Latest update breaks plugin

### ISSUE THREAD

**Issue by Kroesss** [alexpdraper/reading-list#98]
The add-on updated today, and after that it is not saving new additions anymore. It also shows the complete list of all entries that were saved before, but deleted from the list in the past.

**Comment by alekksander** [comment]
same here

**Comment by TeleCasterTube** [comment]
Same here... Had to delete the whole list. Some new additions get saved others don't (tracking packages DHL not working as an example)

**Comment by whitecat** [comment]
We are looking at the update

**Comment by TeleCasterTube** [comment]
> We are looking at the update

Thanks!

**Comment by whitecat** [comment]
Please post what operating system you are using. We are having difficulties reproducing any problems with the app.

**Comment by TeleCasterTube** [comment]
10.14.6 (18G103) Mojave Firefox 80.0 (64-bit)

**Comment by whitecat** [comment]
Yes but are you using windows or Mac?

**Comment by TeleCasterTube** [comment]
Mojave = MAC

**Comment by Kroesss** [comment]
Windows 10

**Comment by whitecat** [comment]
Couple more questions.
Are you signed into Firefox?
Do you have Sync turned on?
How many websites do you have saved?

Thank you for your patience. I am still having difficulties reproducing the bug locally. 

I have found one bug https://github.com/alexpdraper/reading-list/issues/99.  But I do not believe that is the same bug you all are facing.

**Comment by TeleCasterTube** [comment]
Are you signed into Firefox? Yes
Do you have Sync turned on? Yes
How many websites do you have saved? About 25

**Comment by whitecat** [comment]
I will be looking into this today.

**Comment by TeleCasterTube** [comment]
Thanks!

**Comment by Kroesss** [comment]
Are you signed into Firefox? No
Do you have Sync turned on? No
How many websites do you have saved? this varies. Sometimes just a 3 or 4, sometimes up to 25.

**Comment by TeleCasterTube** [comment]
Bug #99 is part of the problem. If the list is cleaned out all is working for the moment (I think) except some sites don't stick

**Comment by whitecat** [comment]
I have pushed an update. I started the process to get Firefox to review our app. Should be done soon, if you want it now feel free to build manually.
